services:
  backend:
    build:
      context: ./fastapi-backend  # Path to backend directory
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000

  frontend:
    build:
      context: ./fastapi-frontend  # Path to frontend directory
    ports:
      - "3000:80"

